version: '3'
services:
  v2board:
    image: tokumeikoi/lcrp
    volumes:
      - '/root/V2Board/v2board-docker/www:/www'
      - '/root/V2Board/v2board-docker/wwwlogs:/wwwlogs'
      - '/root/V2Board/v2board-docker/caddy.conf:/run/caddy/caddy.conf'
      - '/root/V2Board/v2board-docker/supervisord.conf:/run/supervisor/supervisord.conf'
      - '/root/V2Board/v2board-docker/crontabs.conf:/etc/crontabs/root'
      - '/root/V2Board/v2board-docker/caddy:/root/.caddy'
    ports:
      - '80:80'
      - '443:443'
    restart: always
